namespace pkuManager
{
    public enum RibbonIndex
    {
        // Contest Gen 3
        CoolG3 = -49, //Indexing starts at -49 because memory ribbons replaced old contest/battle ribbons
        CoolSuperG3,
        CoolHyperG3,
        CoolMasterG3,
        BeautyG3,
        BeautySuperG3,
        BeautyHyperG3,
        BeautyMasterG3,
        CuteG3,
        CuteSuperG3,
        CuteHyperG3,
        CuteMasterG3,
        SmartG3,
        SmartSuperG3,
        SmartHyperG3,
        SmartMasterG3,
        ToughG3,
        ToughSuperG3,
        ToughHyperG3,
        ToughMasterG3,

        // Contest Gen 4
        CoolG4,
        CoolSuperG4,
        CoolHyperG4,
        CoolMasterG4,
        BeautyG4,
        BeautySuperG4,
        BeautyHyperG4,
        BeautyMasterG4,
        CuteG4,
        CuteSuperG4,
        CuteHyperG4,
        CuteMasterG4,
        SmartG4,
        SmartSuperG4,
        SmartHyperG4,
        SmartMasterG4,
        ToughG4,
        ToughSuperG4,
        ToughHyperG4,
        ToughMasterG4,

        // Battle Gen 3-4
        Winning,
        Victory,
        Ability,
        GreatAbility,
        DoubleAbility,
        MultiAbility,
        PairAbility,
        WorldAbility,
        
        // -1 reserved for no match

        // Everything else
        ChampionKalos = 0,
        Champion,
        ChampionSinnoh,
        BestFriends,
        Training,
        BattlerSkillful,
        BattlerExpert,
        Effort,
        Alert,
        Shock,
        Downcast,
        Careless,
        Relax,
        Snooze,
        Smile,
        Gorgeous,
        Royal,
        GorgeousRoyal,
        Artist,
        Footprint,
        Record,
        Legend,
        Country,
        National,
        Earth,
        World,
        Classic,
        Premier,
        Event,
        Birthday,
        Special,
        Souvenir,
        Wishing,
        ChampionBattle,
        ChampionRegional,
        ChampionNational,
        ChampionWorld,
        MemoryContest,
        MemoryBattle,
        ChampionHoenn,
        ContestStar,
        MasterCoolness,
        MasterBeauty,
        MasterCuteness,
        MasterCleverness,
        MasterToughness,
        ChampionAlola,
        BattleRoyale,
        BattleTreeGreat,
        BattleTreeMaster,
        ChampionGalar,
        TowerMaster,
        MasterRank,

        // Marks Gen 8
        MarkLunchtime,
        MarkSleepyTime,
        MarkDusk,
        MarkDawn,
        MarkCloudy,
        MarkRainy,
        MarkStormy,
        MarkSnowy,
        MarkBlizzard,
        MarkDry,
        MarkSandstorm,
        MarkMisty,
        MarkDestiny,
        MarkFishing,
        MarkCurry,
        MarkUncommon,
        MarkRare,
        MarkRowdy,
        MarkAbsentMinded,
        MarkJittery,
        MarkExcited,
        MarkCharismatic,
        MarkCalmness,
        MarkIntense,
        MarkZonedOut,
        MarkJoyful,
        MarkAngry,
        MarkSmiley,
        MarkTeary,
        MarkUpbeat,
        MarkPeeved,
        MarkIntellectual,
        MarkFerocious,
        MarkCrafty,
        MarkScowling,
        MarkKindly,
        MarkFlustered,
        MarkPumpedUp,
        MarkZeroEnergy,
        MarkPrideful,
        MarkUnsure,
        MarkHumble,
        MarkThorny,
        MarkVigor,
        MarkSlump,
    }

    public enum MarkingIndex
    {
        BlueCircle,
        BlueTriangle,
        BlueSquare,
        BlueHeart,
        BlueStar,
        BlueDiamond,
        PinkCircle,
        PinkTriangle,
        PinkSquare,
        PinkHeart,
        PinkStar,
        PinkDiamond,
        Favorite
    }

    public enum EXPGrowthIndex
    {
        MediumFast,
        Erratic,
        Fluctuating,
        MediumSlow,
        Fast,
        Slow
    }

    public enum Gender
    {
        Male,
        Female,
        Genderless
    }
}
