using System;
using System.Drawing;
using System.Windows.Forms;

namespace pkuManager.Alerts
{
    // Essentially just a warning box right now.
    // Extend to errorpanels too (one with radio buttons, one with checkboxes, one with title in red with fatal message, ...)
    public class AlertBox : Panel
    {
        protected Label titleLabel;
        protected TextBox messageTextbox;

        // Creates a new AlertBox (which is just a pre-formatted Panel)
        public AlertBox(string title, string message)
        {
            titleLabel = new Label();
            messageTextbox = newTextBox(message);

            this.Controls.Add(titleLabel);
            this.Controls.Add(messageTextbox);

            this.MinimumSize = new Size(169, 10); //30 height
            this.MaximumSize = new Size(169, 200);
            this.BorderStyle = BorderStyle.FixedSingle;
            this.AutoSize = true;

            titleLabel.Location = new Point(4, 4);
            titleLabel.MaximumSize = new Size(155, 13);
            titleLabel.MinimumSize = new Size(0, 13);
            titleLabel.Text = title;
            titleLabel.Font = new Font(titleLabel.Font, FontStyle.Bold);
            titleLabel.Height = 13;
            titleLabel.Width = titleLabel.PreferredWidth;

            messageTextbox.Location = new Point(7, 20);
        }

        // Creates a textbox formatted to look like a warning/error box
        protected static TextBox newTextBox(string text)
        {
            TextBox tb = new TextBox();
            tb.TextChanged += new EventHandler(textBox_TextChanged);
            tb.MaximumSize = new Size(155, 200);
            tb.MinimumSize = new Size(155, 10);
            tb.Text = text;
            tb.TabStop = false;
            tb.BorderStyle = BorderStyle.None;
            tb.ReadOnly = true;
            tb.Multiline = true;

            return tb;
        }

        // Event handler for when a textbox (generated by newTextBox) is updated (i.e. resizes to fit new text).
        protected static void textBox_TextChanged(object sender, EventArgs e)
        {
            TextBox tb = (TextBox)sender;
            Size size = TextRenderer.MeasureText(tb.Text, tb.Font, new Size(155, 200), TextFormatFlags.WordBreak);
            tb.Height = size.Height;
        }
    }
}
