using pkuManager.Alerts;
using System;
using System.Drawing;
using System.Windows.Forms;

namespace pkuManager.GUI;

/// <summary>
/// A GUI container for basic Alerts. To be used in conjunction with the porter windows.
/// </summary>
public class AlertBox : Panel
{
    protected Label titleLabel;
    protected RichTextBox messageTextbox;

    protected virtual int boxWidth => 169;
    protected virtual int boxMaxHeight => 300;
    protected virtual int textBoxMaxWidth => 155;
    protected virtual int textBoxMaxHeight => 200;

    // Creates a new AlertBox (which is just a pre-formatted Panel)
    public AlertBox(Alert alert)
    {
        titleLabel = new();
        messageTextbox = newRichTextBox(alert.Message);

        Controls.Add(titleLabel);
        Controls.Add(messageTextbox);

        MinimumSize = new(boxWidth, 10); //30 height
        MaximumSize = new(boxWidth, boxMaxHeight);
        BorderStyle = BorderStyle.FixedSingle;
        AutoSize = true;

        titleLabel.Location = new(4, 4);
        titleLabel.MaximumSize = new(textBoxMaxWidth, 15);
        titleLabel.MinimumSize = new(0, 15);
        titleLabel.Text = alert.Title;
        titleLabel.Font = new(titleLabel.Font, FontStyle.Bold);
        titleLabel.Width = titleLabel.PreferredWidth;

        messageTextbox.Location = new(7, 20);
    }

    // Creates a textbox formatted to look like a warning/error box
    protected TextBox newTextBox(string text, int? maxwidth = null, int? maxheight = null)
    {
        if (maxwidth is null) maxwidth = textBoxMaxWidth;
        if (maxheight is null) maxheight = textBoxMaxHeight;

        TextBox tb = new();
        tb.TextChanged += new(textBox_TextChanged);
        tb.MaximumSize = new(maxwidth.Value, maxheight.Value);
        tb.MinimumSize = new(maxwidth.Value, 10);
        tb.Text = text;
        tb.Multiline = true;
        tb.BorderStyle = BorderStyle.None;
        //tb.TabStop = false;
        //tb.ReadOnly = true;

        return tb;
    }

    // Creates a richtextbox formatted to look like a warning/error box
    protected RichTextBox newRichTextBox(string text, int? maxwidth = null, int? maxheight = null)
    {
        if (maxwidth is null) maxwidth = textBoxMaxWidth;
        if (maxheight is null) maxheight = textBoxMaxHeight;

        TextBox test = newTextBox(text, maxwidth, maxheight);

        RichTextBox tb = new();
        tb.TextChanged += new(textBox_TextChanged);
        tb.MaximumSize = new(maxwidth.Value, maxheight.Value);
        tb.MinimumSize = new(maxwidth.Value, 10);
        tb.Text = text;
        tb.BorderStyle = BorderStyle.None;
        tb.TabStop = false;
        tb.ReadOnly = true;
        tb.Multiline = true;
        tb.Size = test.Size;

        return tb;
    }

    // Event handler for when a textbox (generated by newTextBox) is updated (i.e. resizes to fit new text).
    protected static void textBox_TextChanged(object sender, EventArgs e)
    {
        TextBox tb = sender as TextBox;
        Size size = TextRenderer.MeasureText(tb.Text, tb.Font, tb.MaximumSize, TextFormatFlags.WordBreak);
        tb.Height = size.Height;
    }
}