//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pkuManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pkuManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None
        ///Stench
        ///Drizzle
        ///Speed Boost
        ///Battle Armor
        ///Sturdy
        ///Damp
        ///Limber
        ///Sand Veil
        ///Static
        ///Volt Absorb
        ///Water Absorb
        ///Oblivious
        ///Cloud Nine
        ///Compound Eyes
        ///Insomnia
        ///Color Change
        ///Immunity
        ///Flash Fire
        ///Shield Dust
        ///Own Tempo
        ///Suction Cups
        ///Intimidate
        ///Shadow Tag
        ///Rough Skin
        ///Wonder Guard
        ///Levitate
        ///Effect Spore
        ///Synchronize
        ///Clear Body
        ///Natural Cure
        ///Lightning Rod
        ///Serene Grace
        ///Swift Swim
        ///Chlorophyll
        ///Illuminate
        ///Trace
        ///Huge Power
        ///Poison Point
        ///Inner Focus
        ///Magma Armor
        ///Water Veil
        ///Magnet Pull
        ///Soundproo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Abilities {
            get {
                return ResourceManager.GetString("Abilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap egg {
            get {
                object obj = ResourceManager.GetObject("egg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap egg_manaphy {
            get {
                object obj = ResourceManager.GetObject("egg_manaphy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None / Pal Park / Egg
        ///Rock Smash (HGSS) / Rock Smash
        ///Tall Grass / Newmoon Island
        ///
        ///Dialga/Palkia / Spear Pillar
        ///Cave/Hall of Origin / Cave / Hall of Origin
        ///
        ///Surfing/Fishing / Surfing / Fishing
        ///
        ///Building/Enigma Stone / Building / Enigma Stone
        ///Marsh/Safari / Marsh
        ///
        ///Starter/Fossil/Gift (DP) / Starter (DP/HGSS) / Fossil (DP) / Gift (DP)
        ///JUMP TO / 23
        ///Distortion World (Pt) / Distortion World
        ///Starter/Fossil/Gift (Pt/DP Trio) / Starter (Pt) / Fossil (Pt/HGSS) / Gift (Pt/HGSS) / Sinjoh Ruins.
        /// </summary>
        internal static string EncounterTypesENG {
            get {
                return ResourceManager.GetString("EncounterTypesENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None
        ///Sapphire
        ///Ruby
        ///Emerald
        ///FireRed
        ///LeafGreen
        ///
        ///HeartGold
        ///SoulSilver
        ///
        ///Diamond
        ///Pearl
        ///Platinum
        ///
        ///
        ///Colosseum / XD
        ///
        ///
        ///
        ///
        ///White
        ///Black
        ///White 2
        ///Black 2
        ///X
        ///Y
        ///Alpha Sapphire
        ///Omega Ruby
        ///
        ///
        ///Sun
        ///Moon
        ///Ultra Sun
        ///Ultra Moon
        ///Pokemon GO
        ///Red
        ///Blue / Green
        ///Blue(JP)
        ///Yellow
        ///Gold
        ///Silver
        ///Crystal
        ///Let&apos;s Go, Pikachu!
        ///Let&apos;s Go, Eevee!
        ///Sword
        ///Shield.
        /// </summary>
        internal static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red / Blue / Green / Blue(JP) / Yellow
        ///Gold / Silver / Crystal
        ///Sapphire / Ruby / Emerald / FireRed / LeafGreen
        ///Colosseum
        ///XD
        ///Diamond / Pearl / Platinum / HeartGold / SoulSilver
        ///Battle Revolution
        ///White / Black / White 2 / Black 2
        ///X / Y / Alpha Sapphire / Omega Ruby
        ///Sun / Moon / Ultra Sun / Ultra Moon
        ///Let&apos;s Go, Pikachu! / Let&apos;s Go, Eevee!
        ///Sword / Shield.
        /// </summary>
        internal static string GamesToFormat {
            get {
                return ResourceManager.GetString("GamesToFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grassbox {
            get {
                object obj = ResourceManager.GetObject("grassbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None
        ///JPN / Japanese
        ///ENG / English
        ///FRE / French
        ///ITA / Italian
        ///GER / German
        ///
        ///SPA / Spanish
        ///KOR / Korean
        ///CHS / Chinese Simplified
        ///CHT / Chinese Traditional.
        /// </summary>
        internal static string LangENG {
            get {
                return ResourceManager.GetString("LangENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Circle / Circle
        ///Blue Triangle / Triangle
        ///Blue Square / Square
        ///Blue Heart / Heart
        ///Blue Star / Star
        ///Blue Diamond / Diamond
        ///Pink Circle
        ///Pink Triangle
        ///Pink Square
        ///Pink Heart
        ///Pink Star
        ///Pink Diamond
        ///Favorite.
        /// </summary>
        internal static string MarkingsENG {
            get {
                return ResourceManager.GetString("MarkingsENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None
        ///Pound
        ///Karate Chop
        ///Double Slap
        ///Comet Punch
        ///Mega Punch
        ///Pay Day
        ///Fire Punch
        ///Ice Punch
        ///Thunder Punch
        ///Scratch
        ///Vise Grip
        ///Guillotine
        ///Razor Wind
        ///Swords Dance
        ///Cut
        ///Gust
        ///Wing Attack
        ///Whirlwind
        ///Fly
        ///Bind
        ///Slam
        ///Vine Whip
        ///Stomp
        ///Double Kick
        ///Mega Kick
        ///Jump Kick
        ///Rolling Kick
        ///Sand Attack
        ///Headbutt
        ///Horn Attack
        ///Fury Attack
        ///Horn Drill
        ///Tackle
        ///Body Slam
        ///Wrap
        ///Take Down
        ///Thrash
        ///Double-Edge
        ///Tail Whip
        ///Poison Sting
        ///Twineedle
        ///Pin Missile
        ///Leer
        ///Bite
        ///Growl
        ///Roar
        ///Sing
        ///Supersonic
        ///Sonic Boom
        ///Di [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Moves {
            get {
                return ResourceManager.GetString("Moves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    // Pokemon from gens 1-8
        ///    // Gender Differences tags for pokemon from Gens 1-4
        ///    &quot;Bulbasaur&quot;: {
        ///        &quot;National Dex&quot;: 1
        ///    },
        ///    &quot;Ivysaur&quot;: {
        ///        &quot;National Dex&quot;: 2
        ///    },
        ///    &quot;Venusaur&quot;: {
        ///        &quot;National Dex&quot;: 3,
        ///        &quot;Gender Differences&quot;: true
        ///    },
        ///    &quot;Charmander&quot;: {
        ///        &quot;National Dex&quot;: 4
        ///    },
        ///    &quot;Charmeleon&quot;: {
        ///        &quot;National Dex&quot;: 5
        ///    },
        ///    &quot;Charizard&quot;: {
        ///        &quot;National Dex&quot;: 6
        ///    },
        ///    &quot;Squirtle&quot;: {
        ///        &quot;National Dex&quot;: 7
        ///    },
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nationaldexData {
            get {
                return ResourceManager.GetString("nationaldexData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardy
        ///Lonely
        ///Brave
        ///Adamant
        ///Naughty
        ///Bold
        ///Docile
        ///Relaxed
        ///Impish
        ///Lax
        ///Timid
        ///Hasty
        ///Serious
        ///Jolly
        ///Naive
        ///Modest
        ///Mild
        ///Quiet
        ///Bashful
        ///Rash
        ///Calm
        ///Gentle
        ///Sassy
        ///Careful
        ///Quirky.
        /// </summary>
        internal static string Natures {
            get {
                return ResourceManager.GetString("Natures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon pc {
            get {
                object obj = ResourceManager.GetObject("pc", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Littleroot Town
        ///Oldale Town
        ///Dewford Town
        ///Lavaridge Town
        ///Fallarbor Town
        ///Verdanturf Town
        ///Pacifidlog Town
        ///Petalburg City
        ///Slateport City
        ///Mauville City
        ///Rustboro City
        ///Fortree City
        ///Lilycove City
        ///Mossdeep City
        ///Sootopolis City
        ///Ever Grande City
        ///Route 101
        ///Route 102
        ///Route 103
        ///Route 104
        ///Route 105
        ///Route 106
        ///Route 107
        ///Route 108
        ///Route 109
        ///Route 110
        ///Route 111
        ///Route 112
        ///Route 113
        ///Route 114
        ///Route 115
        ///Route 116
        ///Route 117
        ///Route 118
        ///Route 119
        ///Route 120
        ///Route 121
        ///Route 122
        ///Route 123
        ///Route 12 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pk3Locations {
            get {
                return ResourceManager.GetString("pk3Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Master Ball
        ///Master Ball
        ///Ultra Ball
        ///Great Ball
        ///Poke Ball / Poké Ball / Pokeball
        ///Safari Ball
        ///Net Ball
        ///Dive Ball
        ///Nest Ball
        ///Repeat Ball
        ///Timer Ball
        ///Luxury Ball
        ///Premier Ball
        ///Dusk Ball
        ///Heal Ball
        ///Quick Ball
        ///Cherish Ball
        ///Fast Ball
        ///Level Ball
        ///Lure Ball
        ///Heavy Ball
        ///Love Ball
        ///Friend Ball
        ///Sport Ball.
        /// </summary>
        internal static string pk4BallsENG {
            get {
                return ResourceManager.GetString("pk4BallsENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUMP TO / 172
        ///Normal / Spiky-eared
        ///JUMP TO / 201
        ///A / B / C / D / F / G / H / I / J / K / L / M / N / O / P / Q / R / S / T / U / V / W / X / Y / Z / ! / ?
        ///JUMP TO / 386
        ///Normal / Attack / Defense / Speed
        ///JUMP TO / 412
        ///Plant Cloak / Sandy Cloak / Trash Cloak
        ///Plant Cloak / Sandy Cloak / Trash Cloak
        ///JUMP TO / 422
        ///West Sea / East Sea
        ///JUMP TO / 479
        ///Normal / Heat / Wash / Frost / Fan / Mow
        ///JUMP TO / 487
        ///Altered / Origin
        ///JUMP TO / 492
        ///Land / Sky
        ///JUMP TO / 493
        ///Normal / Fighting / Flying / Poison /  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pk4FormsENG {
            get {
                return ResourceManager.GetString("pk4FormsENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None
        ///Master Ball
        ///Ultra Ball
        ///Great Ball
        ///Poké Ball / PokéBall / Poke Ball / PokeBall
        ///Safari Ball
        ///Net Ball
        ///Dive Ball
        ///Nest Ball
        ///Repeat Ball
        ///Timer Ball
        ///Luxury Ball
        ///Premier Ball
        ///Dusk Ball
        ///Heal Ball
        ///Quick Ball
        ///Cherish Ball
        ///Potion
        ///Antidote
        ///Burn Heal
        ///Ice Heal
        ///Awakening
        ///Parlyz Heal
        ///Full Restore
        ///Max Potion
        ///Hyper Potion
        ///Super Potion
        ///Full Heal
        ///Revive
        ///Max Revive
        ///Fresh Water
        ///Soda Pop
        ///Lemonade
        ///Moomoo Milk
        ///EnergyPowder
        ///Energy Root
        ///Heal Powder
        ///Revival Herb
        ///Ether
        ///Max Ether
        ///Elixir
        ///Max E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pk4ItemsENG {
            get {
                return ResourceManager.GetString("pk4ItemsENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mystery Zone (Map)
        ///Twinleaf Town
        ///Sandgem Town
        ///Floaroma Town
        ///Solaceon Town
        ///Celestic Town
        ///Jubilife City
        ///Canalave City
        ///Oreburgh City
        ///Eterna City
        ///Hearthome City
        ///Pastoria City
        ///Veilstone City
        ///Sunyshore City
        ///Snowpoint City
        ///Pokémon League
        ///Route 201
        ///Route 202
        ///Route 203
        ///Route 204
        ///Route 205
        ///Route 206
        ///Route 207
        ///Route 208
        ///Route 209
        ///Route 210
        ///Route 211
        ///Route 212
        ///Route 213
        ///Route 214
        ///Route 215
        ///Route 216
        ///Route 217
        ///Route 218
        ///Route 219
        ///Route 220
        ///Route 221
        ///Route 222
        ///Route 223
        ///Route 224
        ///R [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pk4Locations {
            get {
                return ResourceManager.GetString("pk4Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon pkuicon {
            get {
                object obj = ResourceManager.GetObject("pkuicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon pkulogo {
            get {
                object obj = ResourceManager.GetObject("pkulogo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;001&quot;: {
        ///    &quot;idx&quot;: &quot;001&quot;,
        ///    &quot;name&quot;: {
        ///      &quot;eng&quot;: &quot;Bulbasaur&quot;,
        ///      &quot;chs&quot;: &quot;妙蛙种子&quot;,
        ///      &quot;jpn&quot;: &quot;フシギダネ&quot;,
        ///      &quot;jpn_ro&quot;: &quot;Fushigidane&quot;
        ///    },
        ///    &quot;slug&quot;: {
        ///      &quot;eng&quot;: &quot;bulbasaur&quot;,
        ///      &quot;jpn&quot;: &quot;fushigidane&quot;,
        ///      &quot;jpn_ro&quot;: &quot;fushigidane&quot;
        ///    },
        ///    &quot;gen-7&quot;: {
        ///      &quot;forms&quot;: {
        ///        &quot;$&quot;: {
        ///          &quot;has_female&quot;: false,
        ///          &quot;has_right&quot;: false
        ///        }
        ///      }
        ///    },
        ///    &quot;gen-8&quot;: {
        ///      &quot;forms&quot;: {
        ///        &quot;$&quot;: {
        ///          &quot;is_prev_gen_icon&quot;: true
        ///        }
        ///      }
        ///    }
        ///  },
        ///  &quot;002&quot;: {
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pokespriteData {
            get {
                return ResourceManager.GetString("pokespriteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;UFO&quot;: {
        ///        // Doesn&apos;t have dex number, don&apos;t include it
        ///        &quot;Forms&quot;: {
        ///            &quot;Form 1&quot;: {
        ///                &quot;Default&quot;: true,
        ///                &quot;Gen 5 Index&quot;: 652,
        ///                &quot;Languages&quot;: {
        ///                    &quot;English&quot;: &quot;Form 1&quot; // For display/translating purposes only
        ///                }
        ///            },
        ///            &quot;Prop 1&quot;: { //Prop U1
        ///                //don&apos;t include &quot;Default&quot;: false, less clutter
        ///                &quot;Gen 5 Index&quot;: 664,
        ///                &quot;Not Grounded&quot;:  true, / [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pokestarData {
            get {
                return ResourceManager.GetString("pokestarData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUMP TO / -49
        ///Cool G3
        ///Cool Super G3
        ///Cool Hyper G3
        ///Cool Master G3
        ///Beauty G3
        ///Beauty Super G3
        ///Beauty Hyper G3
        ///Beauty Master G3
        ///Cute G3
        ///Cute Super G3
        ///Cute Hyper G3
        ///Cute Master G3
        ///Smart G3 / Clever G3
        ///Smart Super G3 / Clever Super G3 
        ///Smart Hyper G3 / Clever Hyper G3
        ///Smart Master G3 / Clever Master G3
        ///Tough G3
        ///Tough Super G3
        ///Tough Hyper G3
        ///Tough Master G3
        ///Cool G4
        ///Cool Great G4
        ///Cool Ultra G4
        ///Cool Master G4
        ///Beauty G4
        ///Beauty Great G4
        ///Beauty Ultra G4
        ///Beauty Master G4
        ///Cute G4
        ///Cute Great  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ribbons {
            get {
                return ResourceManager.GetString("Ribbons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap selection {
            get {
                object obj = ResourceManager.GetObject("selection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    // showdownItems.txt is as of 1/20/21
        ///    // this is as of 1/20/21
        ///
        ///    // gen 5,6 everything but megas and regional
        ///    // gen 7,8, need everything
        ///
        ///    // Gen 1
        ///    &quot;Venusaur&quot;: {
        ///        &quot;Forms&quot;: {
        ///            &quot;Mega&quot;: {
        ///                &quot;Showdown Species&quot;: &quot;Venusaur-Mega&quot;
        ///            }
        ///        }
        ///    }, //3
        ///    &quot;Charizard&quot;: {
        ///        &quot;Forms&quot;: {
        ///            &quot;Mega X&quot;: {
        ///                &quot;Showdown Species&quot;: &quot;Charizard-Mega-X&quot;
        ///            },
        ///            &quot;Mega Y&quot;: {
        ///                &quot;Sho [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string showdownData {
            get {
                return ResourceManager.GetString("showdownData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abomasite
        ///Absolite
        ///Absorb Bulb
        ///Adamant Orb
        ///Adrenaline Orb
        ///Aerodactylite
        ///Aggronite
        ///Aguav Berry
        ///Air Balloon
        ///Alakazite
        ///Aloraichium Z
        ///Altarianite
        ///Ampharosite
        ///Apicot Berry
        ///Armor Fossil
        ///Aspear Berry
        ///Assault Vest
        ///Audinite
        ///Babiri Berry
        ///Banettite
        ///Beast Ball
        ///Beedrillite
        ///Belue Berry
        ///Berry Juice
        ///Berry Sweet
        ///Big Root
        ///Binding Band
        ///Black Belt
        ///Black Sludge
        ///Black Glasses
        ///Blastoisinite
        ///Blazikenite
        ///Blue Orb
        ///Bluk Berry
        ///Blunder Policy
        ///Bottle Cap
        ///Bright Powder
        ///Bug Gem
        ///Bug Memory
        ///Buginium Z        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string showdownItems {
            get {
                return ResourceManager.GetString("showdownItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Pichu&quot;: {
        ///        &quot;Forms&quot;: {
        ///            &quot;Spiky-eared&quot;: {
        ///                &quot;Bulbapedia Suffix&quot;: &quot;N&quot;
        ///            }
        ///        }
        ///    },
        ///    &quot;Unown&quot;: {
        ///        &quot;Forms&quot;: {
        ///            &quot;A&quot;: {
        ///                &quot;Bulbapedia Suffix&quot;: &quot;&quot;
        ///            },
        ///            &quot;B&quot;: {
        ///                &quot;Bulbapedia Suffix&quot;: &quot;-B&quot;
        ///            },
        ///            &quot;C&quot;: {
        ///                &quot;Bulbapedia Suffix&quot;: &quot;-C&quot;
        ///            },
        ///            &quot;D&quot;: {
        ///                &quot;Bulbapedia Suffix&quot;: &quot;-D&quot;
        ///            },
        ///            &quot;E&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string spriteData {
            get {
                return ResourceManager.GetString("spriteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unknown {
            get {
                object obj = ResourceManager.GetObject("unknown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unknown2 {
            get {
                object obj = ResourceManager.GetObject("unknown2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
